#cloud-config
write_files:
  - path: /etc/nixos/host.nix
    permissions: "0644"
    content: |
      {pkgs, ...}:
      {
        environment.systemPackages = with pkgs; [ vim jdk openssh minecraft-server ];
      }
  - path: /etc/nixos/users.nix
    permissions: "0644"
    content: |
      {pkgs, ...}:
      {
        users.mutableUsers = false;
        users.users.minecraft = {
          isNormalUser = true;
          home  = "/home/minecraft";
          description  = "minecraft admind";
          extraGroups  = [ ];
          openssh.authorizedKeys.keys  = [ "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeuiXl+pwPiFRS+jwORp7r3S9Rcp1y7sYxOjaqHD0Yj0Q6vvmasbZX1pUJiKSaZbzfe3nqEbjd5qBiywi/AnPjMFmT2dXYfOTE4g82VmtM2Pq5jWP9wishrLgZ6+2AjYEs4wJo5oYKEvFCGvxh0T9+2dhEEoDjcR+Yq6Xl5vG/36Rf+tqA7zwa8dagbVZInqgiFjsWQffh1H4w1/3j3mr6YlJmEfSJGv6dGS+Zy/jXNF2vUrRtgXakGDtT1EB4MjdtbMu2kH9iXLz4yBFenpQIHEcZYsXjWcs0w3X6HUai1GZuT83nRyjdqFJmD3CExquyy/LuklvcVZfjZYMUV+mrJElfQH1ZsB+fe0t8sYVJanec8tgWcElWCdjYhmvItGh6QEiH85LeIYkrRO0yt+kE7AGfZuvcleAe9bF4Byc7Xwtd64GFaSQMAdSIXIAWcghzYZXdfhcB9AFFNC79/9JpVnzxlZ1kc4UDJ7zSy5k6s5lh05eDdzwvYVKVMw7x+sU= dliebgold@Silver-Surfer.local" ];
        };
      }
runcmd:
  - mkdir -p /opt/minecraft
  - cd /opt/minecraft && git clone https://github.com/Danl2620/vm-2024-fall.git
  - curl https://raw.githubusercontent.com/keeakita/nixos-infect/master/nixos-infect | PROVIDER=digitalocean NIXOS_IMPORT=./host.nix NIX_CHANNEL=nixos-23.05 bash 2>&1 | tee /tmp/infect.log
